#define PNG_NO_WRITE_SUPPORTED
#define PNG_NO_MNG_FEATURES
#define PNG_NO_PROGRESSIVE_READ
#define PNG_NO_READ_hIST
#define PNG_iTXt_SUPPORTED

#ifdef __BIG_ENDIAN__
#define PNG_READ_BIG_ENDIAN_SUPPORTED
#endif
